app/client/js/login.service.js, app/client/js/upc.controller.js, app/client/js/upc.service.js, app/client/templates/create-user.template.html
Create user template, created upc service and controllers, added create user functions.
=> Create user template, service  and controller functions

.jshintrc, app/client/index.html, app/client/js/game.module.js, gruntfile.js, package.json
=> added nav links. views work

gruntfile.js, package.json
Added sass folder app/client and sass options to the gruntfile.
=> Added sass options to grunt

app/client/js/login.controller.js, app/client/js/login.service.js, app/client/js/user.controller.js, app/client/js/user.service.js, app/client/templates/create-user.template.html, app/client/templates/login.template.html
Added alerts that display to the user when their form input is not correct and when there are failed status codes.
=> Error handling & alerts

app/client/js/game.module.js, app/client/js/login.controller.js, app/client/js/login.service.js, app/client/js/upc.controller.js, app/client/js/user.controller.js, app/client/js/user.service.js, app/client/templates/create-user.template.html
Fixed controller naming and corrected ng-submit on create user form. Returns correct object and gives proper response code expected with no auth token.
=> Create user form creates object, gets expected 422 response.

app/client/js/user.service.js, app/client/templates/create-user.template.html
=> create user form works. gets and stores a token.

config/routes.rb, db/migrate/20170419204101_add_nutrition_data_to_cards.rb, db/schema.rb, spec/controllers/authorizations_controller_spec.rb
Added jsonb nutrition data and removed a binding.pry mistakenly left in the authorizations spec file
=> Card model

app/client/index.html, app/client/js/game.module.js, app/client/templates/not-found.template.html
added 404 page, added state for not-found and router provider for home path.
=> basic 404 page

app/client/js/game.module.js, app/client/js/upc.controller.js, app/client/js/upc.service.js, app/client/templates/cards.template.html, app/client/templates/create-user.template.html, app/client/templates/login.template.html, app/client/templates/upc.template.html
=> New upc form

app/client/index.html, app/client/js/card.controller.js, app/client/js/card.service.js, app/client/js/game.module.js, app/client/templates/cards.template.html
should display all cards once api endpoint is accessible.
=> created card controller, service, & html template. 

app/client/bootstrap.css, app/client/index.html, app/client/sass/body.scss, app/client/sass/create-user.scss, app/client/sass/header.scss, app/client/sass/home.scss, app/client/sass/login.scss, app/client/sass/main-view.scss, app/client/sass/main.scss, app/client/sass/nav.scss, app/client/sass/upc-form.scss, app/client/sass/variables.scss, app/client/templates/cards.template.html, app/client/templates/create-user.template.html, app/client/templates/home.template.html, app/client/templates/login.template.html, app/client/templates/upc.template.html, gruntfile.js
=> Bootstrappin - added preliminary styles to all existing pages. 

app/client/test/cards.controller.spec.js, app/client/test/user.controller.spec.js
Don't know why this didn't work the first time.
=> renamed more things

app/controllers/api/cards_controller.rb, app/controllers/application_controller.rb, app/models/card.rb, app/models/card_assignment.rb, app/models/card_converter.rb, app/models/user.rb, db/migrate/20170424154408_add_saltto_cards.rb, db/migrate/20170425150038_create_card_assignments.rb, db/schema.rb, spec/controllers/cards_controller_spec.rb, spec/models/card_assignment_spec.rb, spec/models/nutritionix_api_spec.rb
Added tests, created has_many_through relationship with card and user via card assignments, reassigned calories and carbohydrates to different card aspects.
=> Cards table migrations

app/client/js/game.controller.js, app/client/sass/play.scss, app/client/templates/play.template.html
Lots of styling for the game play view including health bars and a faux terminal window for combat text.
=> Implemented player and enemy health bars, added terminal text window.

app/client/sass/end.scss, app/client/sass/lost.scss, app/client/sass/main.scss, app/client/templates/end.template.html, app/client/templates/lost.template.html
Added basic styling for the end of game and lost game views.
=> Basic styles for end and lost templates.

app/client/js/cards.service.js, app/client/js/upc.service.js, app/client/js/user.service.js, db/schema.rb
UPC form works again. Sends auth token.
=> added authorization to all ajax calls. 

app/client/js/cards.controller.js, app/client/js/cards.service.js, app/client/js/game.module.js, app/client/templates/cards.template.html
Pointing card var to response data. Now able to populate the view.
=> Pulling data into the card view

app/client/js/cards.service.js, app/client/js/game.controller.js, app/client/js/game.service.js, app/client/templates/play.template.html
set up game services so that it is ready for api calls. Is also injected into the game controller. All game data is pulled from the service.
=> Removed schema from controller and added it the the game services.

app/client/js/game.controller.js, app/client/js/game.service.js
Fixed a bug that kept the player's health from updating after resetting the game.
=> fixed a health bug

app/client/js/game.controller.js
Fixed the same bug for winning the game condition
=> fixed another bug for player health

app/client/js/cards.controller.js, app/client/js/game.controller.js, app/client/templates/play.template.html
=> fixed variable assignments

spec/client/test/game.controller.spec.js, spec/client/test/game.service.spec.js, spec/client/test/upc.controller.spec.js
Added some basic game.service testing
=> Game testing

app/client/js/cards.controller.js, app/client/js/game.controller.js, gruntfile.js, spec/client/test/cards.controller.spec.js, spec/client/test/cards.service.spec.js, spec/client/test/game.controller.spec.js, spec/client/test/game.service.spec.js, spec/client/test/upc.service.spec.js
=> fixed testing in service spec files, had to add Promise.resolve

app/client/index.html, app/client/sass/cards.scss, app/client/sass/header.scss, app/client/sass/home.scss, app/client/sass/play.scss, app/client/templates/cards.template.html, app/client/templates/home.template.html, app/client/templates/play.template.html, spec/client/test/cards.controller.spec.js
Added play button to go from home page to battle view that is hidden until the player logs in.
=> New play button

app/client/index.html, app/client/sass/header.scss, app/client/sass/play.scss, app/client/templates/play.template.html, spec/client/test/cards.controller.spec.js
all just visual stuff, no functionality changes outside of the css scrolling.
=> changed header to smaller size, changed colors on cards, added scrollbar to terminal

app/client/js/game.module.js
forgot to add the user controller to the home state so the button would work.
=> added controller to home state

app/client/js/cards.controller.js, app/client/js/cards.service.js, app/client/js/upc.controller.js, app/client/js/upc.service.js, app/client/templates/cards.template.html
injected UpcService in the cardcontroller.
=> Single card now getting populated

app/client/index.html, app/client/sass/lost.scss, app/client/sass/main-view.scss, app/client/sass/play.scss, app/client/templates/play.template.html
styling and margins on buttons.
=> Fixed play buttons and text on lost view.

app/client/index.html, app/client/sass/body.scss, app/client/sass/play.scss
sticky header & footer, adjusted margins so that header & footer do not cover up content in main view.
=> fixed header and footer to respective places on page

app/client/sass/play.scss, app/client/templates/play.template.html
Fixed battle view mobile view.
=> Mobile view

app/client/templates/cards.template.html
card created now matches style in play view. Image and name will need to be updated with directives.
=> changed styles on display all cards to match card style in battle view

app/client/js/cards.controller.js, app/client/js/cards.service.js, app/client/js/game.controller.js, app/client/js/game.service.js, app/client/js/upc.controller.js, app/client/templates/cards.template.html, app/client/templates/upc.template.html
Molly and Russel fixed some things in cardbuilder.rb.
=> Card singles

app/client/js/cards.controller.js, app/client/js/cards.service.js, app/client/js/game.controller.js, app/client/templates/cards.template.html, app/client/templates/upc.template.html
Displaying all the cards on the cards view
=> Cards view

app/client/js/cards.controller.js, app/client/templates/upc.template.html
fixed a bug with the cards display
=> bug fix on cards controller

app/client/js/game.controller.js
Added a function to check the health of the end boss and end the game when the boss health reaches 0.
=> 0 health on boss now ends the game correctly

app/client/js/cards.controller.js, app/client/js/cards.service.js
Added function in controller to get the correct card data for the current user card.
=> user card fix

app/client/templates/cards.template.html
added link to the play view on the cards
=> cards link to the play view

app/client/js/game.controller.js, app/client/js/game.service.js
added/changed some content in the bots, treasures, and nothings arrays
=> added some more content to schema

app/client/js/game.controller.js, app/client/js/game.service.js, app/client/templates/play.template.html
Updated the gameservice to include klass key, updated botClass on the gameController, and removed an unneeded class from the play template on the stats li for bot.
=> fixed the char stats on the playtemplate

app/client/templates/about-us.template.html
fixed a small attribute error with p tag
=> class fix in the about us template

app/client/index.html, app/client/js/upc.service.js, app/client/sass/home.scss, app/client/sass/login.scss, app/client/templates/home.template.html, app/client/templates/login.template.html
changed create a user to create an account, emergency UPC form fix, fixed sizing and spelling error on homepage buttons
=> nav fix, UPC form emergency fix, home buttons fix
